### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by mohd4cs** [AbdullahObaid/Mobilyws-Laraval#3]
Hi AbdullahObaid, 
Thanks for your great job! 

If you allow me I have a suggestion in [Mobilyws-Laraval/src/Mobily.php](https://github.com/AbdullahObaid/Mobilyws-Laraval/blob/master/src/Mobily.php)

```php 
public static function Send($numbers, $msg, $dateSend = 0, $timeSend = 0)
{
 .
 .
 .
if ($result == 5) {
   return trans('mobily.wrondpassword');
}
.
.
elseif ($result == 1) {
     return true;
  }
} 

```

You should make **if conditions by common case**, you don't need go through all conditions many times!
for example let make it like that: 
```php 
if ($result == 1) { return true;} 
elseif ( ... ) { ... }
``` 
It becomes at the first condition, because it is our common case .. and so on! 
If we have billions massages it will be much better than current way.

Best regards [M. Saud](https://twitter.com/BenSaud_CS) 🤠

**Comment by AbdullahObaid** [comment]
Thanks, resolved
